In [23]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


### torch simple examples

In [6]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-63, -29, -29, -18,  98, -40])

In [12]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [20]:
linspace = torch.linspace(3, 10, steps=7)
linspace

tensor([ 3.0000,  4.1667,  5.3333,  6.5000,  7.6667,  8.8333, 10.0000])

In [22]:
logspace = torch.logspace(start=-10, end=-10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-10, 1.0000e-10, 1.0000e-10, 1.0000e-10])

In [23]:
eye =torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [27]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

### Torch CPU vs GPU examples

In [2]:
%%time
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

 0.00120282
CPU times: total: 0 ns
Wall time: 1.55 ms


In [3]:
torch_rand1 = torch.rand(1000, 1000).to(device)
torch_rand2 = torch.rand(1000, 1000).to(device)
np_rand1 = torch.rand(1000, 1000)
np_rand2 = torch.rand(1000, 1000)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

 1.60504413
 0.00391364


In [4]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

 0.01016569
 0.36615992


In [5]:
print(torch.__version__)
from platform import python_version
print(python_version())

1.11.0+cu115
3.10.18


In [6]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)


# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [7]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [8]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [9]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [10]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [11]:
torch.exp(out)


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [12]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)
# torch.permute works the same but you provide the new order of dimensions instead of the dimensions you'd like to swap.

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [13]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 7.3973, -0.3268, -7.4403], grad_fn=<SqueezeBackward3>)


In [20]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [15]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 0.0139,  1.3133,  1.7869, -0.9423,  0.5634, -0.1625],
        [ 1.8115, -0.8160, -1.2193,  1.1358, -1.3363, -0.3869],
        [ 0.0920, -1.1742,  0.5357, -1.2338,  0.7943,  0.1472],
        [ 1.2256, -1.2931,  0.5619, -0.3169, -0.2690,  1.2103]],
       grad_fn=<EmbeddingBackward0>)


In [16]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [17]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [20]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [24]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
print(output[:, -1, :])

tensor([[7.3700e-01, 4.6972e-01, 3.1755e-01, 4.9290e-01, 2.2041e-01, 8.6605e-01,
         2.4024e-01, 7.3320e-01, 2.3966e-01, 1.5354e-01],
        [1.8680e-01, 1.3306e-01, 3.0113e-01, 4.5678e-01, 8.3995e-01, 4.1984e-02,
         8.6797e-01, 9.3580e-01, 8.4831e-01, 5.4321e-01],
        [3.2702e-01, 1.4988e-01, 2.1821e-01, 2.3293e-01, 1.0811e-01, 3.8704e-01,
         3.4002e-01, 8.5410e-01, 3.4601e-01, 8.3591e-01],
        [7.9964e-01, 9.1473e-01, 5.4338e-02, 1.6193e-01, 4.7394e-01, 3.1082e-01,
         5.8027e-01, 3.3418e-01, 2.6412e-02, 6.9142e-01],
        [3.5177e-01, 5.4653e-01, 3.2125e-01, 1.5398e-01, 5.7395e-01, 6.6085e-01,
         3.4711e-01, 1.7291e-01, 5.6948e-02, 2.7166e-01],
        [4.5786e-03, 5.7129e-01, 8.2480e-01, 2.4044e-01, 7.2176e-01, 9.3828e-01,
         6.6284e-01, 5.5286e-01, 3.6507e-01, 9.5497e-02],
        [8.0211e-01, 4.4642e-01, 9.9396e-01, 4.9743e-01, 6.8859e-01, 5.2584e-01,
         4.8179e-01, 1.5836e-01, 9.5423e-02, 6.2368e-01],
        [5.2524e-01, 6.2188

IndexError: too many indices for tensor of dimension 2

In [28]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
